# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Begoña Valero
email: email@mail.com
description: > # this means to ignore newlines until "baseurl:"
  Begoña Valero, escritora.
baseurl: "" # the subpath of your site, e.g. /blog
port: 80
#url: "http://192.168.1.21:80" # the base hostname & protocol for your site
url: "http://www.begonavalero.com" # the base hostname & protocol for your site
#url: "https://www.begonavaleroescritora.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
encoding: utf-8
excerpt_separator: <!--end-->
permalink: pretty
future: true

# Category paginator
posts_per_page: 8

collections:
  agenda:
   output: true
   permalink: /:collection/:title

#To do
#Fix disqus comments (maybe require upload to the web)
#upload
#<li><span class="glyphicon glyphicon-envelope"></span>{% include mail.html mayl="b=gon%v%l=ro=scritor%*gm%il+com" id="0"%}</li>
